#  Copyright (c) 2023 Thomas Mathieson.
#  Distributed under the terms of the MIT license.

# This file is auto-generated by Hatchling. As such, do not:
#   - modify
#   - track in version control e.g. be sure to add to .gitignore
__version__ = VERSION = '0.1.1'
